server:
  port: 80

#mysql
spring:
  datasource:
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?userSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

# sql日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
